version: "3.10"
services:
  worker:
    build: .
    environment:
      SESSION_NAME: $SESSION_NAME
      API_ID: $API_ID
      API_HASH: $API_HASH
      OWNER_USERNAME: $OWNER_USERNAME
      BOT_TOKEN: $BOT_TOKEN
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      PMPERMIT: $PMPERMIT
      SUDO_USERS: $SUDO_USERS
      DURATION_LIMIT: $DURATION_LIMIT
      BOT_NAME: $BOT_NAME
